name: Update Fonts

on:
  workflow_dispatch:

# TEMPORARY NOT ACTIVE

jobs:
  update-fonts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Update fonts
        run: yarn update-fonts

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: update fonts'
          add: 'fonts.json stats.json'